//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace int422_123b06.Entities
{
    public partial class Artist
    {
        #region Primitive Properties
    
        public virtual string artist_id
        {
            get;
            set;
        }
    
        public virtual string stage_name
        {
            get;
            set;
        }
    
        public virtual string l_name
        {
            get;
            set;
        }
    
        public virtual string f_name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Album> Albums
        {
            get
            {
                if (_albums == null)
                {
                    var newCollection = new FixupCollection<Album>();
                    newCollection.CollectionChanged += FixupAlbums;
                    _albums = newCollection;
                }
                return _albums;
            }
            set
            {
                if (!ReferenceEquals(_albums, value))
                {
                    var previousValue = _albums as FixupCollection<Album>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAlbums;
                    }
                    _albums = value;
                    var newValue = value as FixupCollection<Album>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAlbums;
                    }
                }
            }
        }
        private ICollection<Album> _albums;

        #endregion
        #region Association Fixup
    
        private void FixupAlbums(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Album item in e.NewItems)
                {
                    item.Artist = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Album item in e.OldItems)
                {
                    if (ReferenceEquals(item.Artist, this))
                    {
                        item.Artist = null;
                    }
                }
            }
        }

        #endregion
    }
}
