//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace int422_123b06.Entities
{
    public partial class artistEntities : ObjectContext
    {
        public const string ConnectionString = "name=artistEntities";
        public const string ContainerName = "artistEntities";
    
        #region Constructors
    
        public artistEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public artistEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public artistEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Album> Albums
        {
            get { return _albums  ?? (_albums = CreateObjectSet<Album>("Albums")); }
        }
        private ObjectSet<Album> _albums;
    
        public ObjectSet<Artist> Artists
        {
            get { return _artists  ?? (_artists = CreateObjectSet<Artist>("Artists")); }
        }
        private ObjectSet<Artist> _artists;
    
        public ObjectSet<Song> Songs
        {
            get { return _songs  ?? (_songs = CreateObjectSet<Song>("Songs")); }
        }
        private ObjectSet<Song> _songs;
    
        public ObjectSet<User_songs> User_songs
        {
            get { return _user_songs  ?? (_user_songs = CreateObjectSet<User_songs>("User_songs")); }
        }
        private ObjectSet<User_songs> _user_songs;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        #endregion
    }
}
