//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace int422_123b06.Entities
{
    public partial class User
    {
        #region Primitive Properties
    
        public virtual string u_user_id
        {
            get;
            set;
        }
    
        public virtual string l_name
        {
            get;
            set;
        }
    
        public virtual string f_name
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<User_songs> User_songs
        {
            get
            {
                if (_user_songs == null)
                {
                    var newCollection = new FixupCollection<User_songs>();
                    newCollection.CollectionChanged += FixupUser_songs;
                    _user_songs = newCollection;
                }
                return _user_songs;
            }
            set
            {
                if (!ReferenceEquals(_user_songs, value))
                {
                    var previousValue = _user_songs as FixupCollection<User_songs>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUser_songs;
                    }
                    _user_songs = value;
                    var newValue = value as FixupCollection<User_songs>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUser_songs;
                    }
                }
            }
        }
        private ICollection<User_songs> _user_songs;

        #endregion
        #region Association Fixup
    
        private void FixupUser_songs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (User_songs item in e.NewItems)
                {
                    item.User = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (User_songs item in e.OldItems)
                {
                    if (ReferenceEquals(item.User, this))
                    {
                        item.User = null;
                    }
                }
            }
        }

        #endregion
    }
}
